//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cpReportDefinitions.PaymentRep {
    
    public partial class rptProgressClaimDetail : rptTemplate {
        private void InitializeComponent() {
            DevExpress.XtraReports.ReportInitializer reportInitializer = new DevExpress.XtraReports.ReportInitializer(this, "cpReportDefinitions.PaymentRep.Claim.rptProgressClaimDetail.repx");

            // Controls
            this.Detail = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("Detail");
            this.PageHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.PageHeaderBand>("PageHeader");
            this.PageFooter = reportInitializer.GetControl<DevExpress.XtraReports.UI.PageFooterBand>("PageFooter");
            this.ClaimDetailsReport = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailReportBand>("ClaimDetailsReport");
            this.TopMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.TopMarginBand>("TopMargin");
            this.BottomMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.BottomMarginBand>("BottomMargin");
            this.headPanel = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPanel>("headPanel");
            this.xrLabel12 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel12");
            this.xrLabel7 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel7");
            this.xrLabel8 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel8");
            this.xrLabel9 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel9");
            this.xrLabel4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel4");
            this.xrLabel5 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel5");
            this.xrLabel6 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel6");
            this.xrLabel3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel3");
            this.xrLabel1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel1");
            this.lbhDescription = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbhDescription");
            this.lbhSellRate = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbhSellRate");
            this.lbhClaim = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbhClaim");
            this.lbhSchedule = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbhSchedule");
            this.lbhSellTotal = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbhSellTotal");
            this.lbReportHeading = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbReportHeading");
            this.lbProject = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbProject");
            this.lbRecordReference = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbRecordReference");
            this.pbLogo = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPictureBox>("pbLogo");
            this.lbFooterText = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbFooterText");
            this.xrPageInfo1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPageInfo>("xrPageInfo1");
            this.Detail_ClaimDetails = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("Detail_ClaimDetails");
            this.Footer_ClaimDetails = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportFooterBand>("Footer_ClaimDetails");
            this.lbTCQty = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbTCQty");
            this.lbTCTotal = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbTCTotal");
            this.lbPCQty = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbPCQty");
            this.lbPCTotal = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbPCTotal");
            this.lbSchedTotal = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbSchedTotal");
            this.lbSchedQty = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbSchedQty");
            this.lbTDTotal = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbTDTotal");
            this.lbTDQty = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbTDQty");
            this.lbUnit = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbUnit");
            this.lbSellRate = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbSellRate");
            this.lbDesc = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbDesc");
            this.lbhReportTotal = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbhReportTotal");
            this.lbTotalSched = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbTotalSched");
            this.lbTotalToDate = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbTotalToDate");
            this.lbTotalPrev = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbTotalPrev");
            this.lbTotalThisClaim = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbTotalThisClaim");
            this.xrCrossBandLine3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCrossBandLine>("xrCrossBandLine3");
            this.xrCrossBandLine2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCrossBandLine>("xrCrossBandLine2");
            this.xrCrossBandLine1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCrossBandLine>("xrCrossBandLine1");

            // Data Sources
            this.objectDataSource1 = reportInitializer.GetDataSource<DevExpress.DataAccess.ObjectBinding.ObjectDataSource>("objectDataSource1");
            this.objectDataSource1.DataSource = typeof(cpModel.Dtos.Report.ProgressClaimVersionReportDto);
        }
        private DevExpress.XtraReports.UI.DetailBand Detail;
        private DevExpress.XtraReports.UI.PageHeaderBand PageHeader;
        private DevExpress.XtraReports.UI.PageFooterBand PageFooter;
        private DevExpress.XtraReports.UI.DetailReportBand ClaimDetailsReport;
        private DevExpress.XtraReports.UI.TopMarginBand TopMargin;
        private DevExpress.XtraReports.UI.BottomMarginBand BottomMargin;
        private DevExpress.XtraReports.UI.XRPanel headPanel;
        private DevExpress.XtraReports.UI.XRLabel xrLabel12;
        private DevExpress.XtraReports.UI.XRLabel xrLabel7;
        private DevExpress.XtraReports.UI.XRLabel xrLabel8;
        private DevExpress.XtraReports.UI.XRLabel xrLabel9;
        private DevExpress.XtraReports.UI.XRLabel xrLabel4;
        private DevExpress.XtraReports.UI.XRLabel xrLabel5;
        private DevExpress.XtraReports.UI.XRLabel xrLabel6;
        private DevExpress.XtraReports.UI.XRLabel xrLabel3;
        private DevExpress.XtraReports.UI.XRLabel xrLabel1;
        private DevExpress.XtraReports.UI.XRLabel lbhDescription;
        private DevExpress.XtraReports.UI.XRLabel lbhSellRate;
        private DevExpress.XtraReports.UI.XRLabel lbhClaim;
        private DevExpress.XtraReports.UI.XRLabel lbhSchedule;
        private DevExpress.XtraReports.UI.XRLabel lbhSellTotal;
        private DevExpress.XtraReports.UI.XRLabel lbReportHeading;
        private DevExpress.XtraReports.UI.XRLabel lbProject;
        private DevExpress.XtraReports.UI.XRLabel lbRecordReference;
        private DevExpress.XtraReports.UI.XRPictureBox pbLogo;
        private DevExpress.XtraReports.UI.XRLabel lbFooterText;
        private DevExpress.XtraReports.UI.XRPageInfo xrPageInfo1;
        private DevExpress.XtraReports.UI.DetailBand Detail_ClaimDetails;
        private DevExpress.XtraReports.UI.ReportFooterBand Footer_ClaimDetails;
        private DevExpress.XtraReports.UI.XRLabel lbTCQty;
        private DevExpress.XtraReports.UI.XRLabel lbTCTotal;
        private DevExpress.XtraReports.UI.XRLabel lbPCQty;
        private DevExpress.XtraReports.UI.XRLabel lbPCTotal;
        private DevExpress.XtraReports.UI.XRLabel lbSchedTotal;
        private DevExpress.XtraReports.UI.XRLabel lbSchedQty;
        private DevExpress.XtraReports.UI.XRLabel lbTDTotal;
        private DevExpress.XtraReports.UI.XRLabel lbTDQty;
        private DevExpress.XtraReports.UI.XRLabel lbUnit;
        private DevExpress.XtraReports.UI.XRLabel lbSellRate;
        private DevExpress.XtraReports.UI.XRLabel lbDesc;
        private DevExpress.XtraReports.UI.XRLabel lbhReportTotal;
        private DevExpress.XtraReports.UI.XRLabel lbTotalSched;
        private DevExpress.XtraReports.UI.XRLabel lbTotalToDate;
        private DevExpress.XtraReports.UI.XRLabel lbTotalPrev;
        private DevExpress.XtraReports.UI.XRLabel lbTotalThisClaim;
        private DevExpress.XtraReports.UI.XRCrossBandLine xrCrossBandLine3;
        private DevExpress.XtraReports.UI.XRCrossBandLine xrCrossBandLine2;
        private DevExpress.XtraReports.UI.XRCrossBandLine xrCrossBandLine1;
        private DevExpress.DataAccess.ObjectBinding.ObjectDataSource objectDataSource1;
    }
}
