// <auto-generated>
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using cpModel.Interfaces;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading;
using System.Threading.Tasks;

namespace cpModel.Models
{
    public partial class CnControlledDoc: ITrackableEntity, IReplicableEntity, ILockableEntity
    {
        public Guid? UniqueId { get; set; }
        public string HrId { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public bool? IsSoftDeleted { get; set; }
        public int CnContDocId { get; set; }
        public int? CnId { get; set; }
        public int? ContDocId { get; set; }
        public bool? InclNotice { get; set; }
        public bool? InclAtt { get; set; }

        [ConcurrencyCheck]
        public int? OptimisticLockField { get; set; }

        public virtual ContractNotice ContractNotice { get; set; }
        public virtual CpDocument CpDocument { get; set; }

        public CnControlledDoc()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>

