// <auto-generated>
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using cpModel.Interfaces;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading;
using System.Threading.Tasks;

namespace cpModel.Models
{
    public partial class ContractNoticeTemplate: ITrackableEntity, IReplicableEntity, ILockableEntity
    {
        public Guid? UniqueId { get; set; }
        public string HrId { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public bool? IsSoftDeleted { get; set; }
        public int ConTempId { get; set; }
        public int? ProjectId { get; set; }
        public string Abbrev { get; set; }
        public string ConTempName { get; set; }
        public string ConTempSubjectHtml { get; set; }
        public string ConTemplateHtml { get; set; }
        public bool? RequiresResponse { get; set; }
        public bool? IsInactive { get; set; }

        [ConcurrencyCheck]
        public int? OptimisticLockField { get; set; }

        // Reverse navigation
        public virtual ICollection<ContractNotice> ContractNotices { get; set; }

        public virtual Project Project { get; set; }

        public ContractNoticeTemplate()
        {
            ContractNotices = new HashSet<ContractNotice>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>

