// <auto-generated>
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using cpModel.Interfaces;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading;
using System.Threading.Tasks;

namespace cpModel.Models
{
    public partial class ControlLineTranslation: ITrackableEntity, IReplicableEntity, ILockableEntity
    {
        public Guid? UniqueId { get; set; }
        public string HrId { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public bool? IsSoftDeleted { get; set; }
        public int ControlLineTranslationId { get; set; }
        public int? ControlLineParentId { get; set; }
        public int? ControlLineReferenceId { get; set; }
        public double? ParentStartCh { get; set; }
        public double? ParentEndCh { get; set; }
        public double? ReferenceStartCh { get; set; }
        public double? ReferenceEndCh { get; set; }
        public double? ParentOffset { get; set; }

        [ConcurrencyCheck]
        public int? OptimisticLockField { get; set; }

        public virtual ControlLine ControlLineParent { get; set; }
        public virtual ControlLine ControlLineReference { get; set; }

        public ControlLineTranslation()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>

