// <auto-generated>
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using cpModel.Interfaces;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading;
using System.Threading.Tasks;

namespace cpModel.Models
{
    public partial class CostCode: ITrackableEntity, IReplicableEntity, ILockableEntity
    {
        public Guid? UniqueId { get; set; }
        public string HrId { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public bool? IsSoftDeleted { get; set; }
        public int CostCodeId { get; set; }
        public string CostCodeName { get; set; }
        public string Description { get; set; }
        public string Unit { get; set; }
        public decimal? BudgetQty { get; set; }
        public decimal? BudgetTotal { get; set; }
        public int? ProjectId { get; set; }
        public bool? UnitQty { get; set; }
        public bool? Inactive { get; set; }

        [ConcurrencyCheck]
        public int? OptimisticLockField { get; set; }

        // Reverse navigation
        public virtual ICollection<CostCodeCustomRegItem> CostCodeCustomRegItems { get; set; }
        public virtual ICollection<DayCost> DayCosts { get; set; }
        public virtual ICollection<DaycostCostCode> DaycostCostCodes { get; set; }
        public virtual ICollection<ForecastDetail> ForecastDetails { get; set; }
        public virtual ICollection<ForecastWlDistro> ForecastWlDistros { get; set; }
        public virtual ICollection<Production> Productions { get; set; }
        public virtual ICollection<PurchaseOrderDetail> PurchaseOrderDetails { get; set; }
        public virtual ICollection<ReceiptDetail> ReceiptDetails { get; set; }
        public virtual ICollection<SchedCostCode> SchedCostCodes { get; set; }
        public virtual ICollection<SiteDiaryCostCode> SiteDiaryCostCodes { get; set; }
        public virtual ICollection<VariationCostCode> VariationCostCodes { get; set; }

        public virtual Project Project { get; set; }

        public CostCode()
        {
            CostCodeCustomRegItems = new HashSet<CostCodeCustomRegItem>();
            DayCosts = new HashSet<DayCost>();
            DaycostCostCodes = new HashSet<DaycostCostCode>();
            ForecastDetails = new HashSet<ForecastDetail>();
            ForecastWlDistros = new HashSet<ForecastWlDistro>();
            Productions = new HashSet<Production>();
            PurchaseOrderDetails = new HashSet<PurchaseOrderDetail>();
            ReceiptDetails = new HashSet<ReceiptDetail>();
            SchedCostCodes = new HashSet<SchedCostCode>();
            SiteDiaryCostCodes = new HashSet<SiteDiaryCostCode>();
            VariationCostCodes = new HashSet<VariationCostCode>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>

