// <auto-generated>
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using cpModel.Interfaces;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading;
using System.Threading.Tasks;

namespace cpModel.Models
{
    public partial class CustomRegisterItem: ITrackableEntity, IReplicableEntity, ILockableEntity
    {
        public Guid? UniqueId { get; set; }
        public string HrId { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public bool? IsSoftDeleted { get; set; }
        public int CustomRegisterItemId { get; set; }
        public int? CustomRegisterId { get; set; }
        public string CustomRegisterValue { get; set; }
        public string ShortCode { get; set; }
        public bool? RequiresText { get; set; }
        public decimal? OrderId { get; set; }

        [ConcurrencyCheck]
        public int? OptimisticLockField { get; set; }

        // Reverse navigation
        public virtual ICollection<CnCustomRegItem> CnCustomRegItems { get; set; }
        public virtual ICollection<CostCodeCustomRegItem> CostCodeCustomRegItems { get; set; }
        public virtual ICollection<CustomRegisterValue> CustomRegisterValues { get; set; }
        public virtual ICollection<DaycostCustomRegItem> DaycostCustomRegItems { get; set; }
        public virtual ICollection<InvoiceCustomRegItem> InvoiceCustomRegItems { get; set; }
        public virtual ICollection<LotCustomRegItem> LotCustomRegItems { get; set; }
        public virtual ICollection<LotMapLayer> LotMapLayers { get; set; }
        public virtual ICollection<NcrCustomRegItem> NcrCustomRegItems { get; set; }
        public virtual ICollection<QtyCustomRegItem> QtyCustomRegItems { get; set; }
        public virtual ICollection<TestReqCustomRegItem> TestReqCustomRegItems { get; set; }
        public virtual ICollection<VariationCustomRegItem> VariationCustomRegItems { get; set; }

        public virtual CustomRegister CustomRegister { get; set; }

        public CustomRegisterItem()
        {
            CnCustomRegItems = new HashSet<CnCustomRegItem>();
            CostCodeCustomRegItems = new HashSet<CostCodeCustomRegItem>();
            CustomRegisterValues = new HashSet<CustomRegisterValue>();
            DaycostCustomRegItems = new HashSet<DaycostCustomRegItem>();
            InvoiceCustomRegItems = new HashSet<InvoiceCustomRegItem>();
            LotCustomRegItems = new HashSet<LotCustomRegItem>();
            LotMapLayers = new HashSet<LotMapLayer>();
            NcrCustomRegItems = new HashSet<NcrCustomRegItem>();
            QtyCustomRegItems = new HashSet<QtyCustomRegItem>();
            TestReqCustomRegItems = new HashSet<TestReqCustomRegItem>();
            VariationCustomRegItems = new HashSet<VariationCustomRegItem>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>

