// <auto-generated>
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using cpModel.Interfaces;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading;
using System.Threading.Tasks;

namespace cpModel.Models
{
    public partial class CustomRegisterValue: ITrackableEntity, IReplicableEntity, ILockableEntity
    {
        public Guid? UniqueId { get; set; }
        public string HrId { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public bool? IsSoftDeleted { get; set; }
        public int CustomRegisterValueId { get; set; }
        public int? RegisterId { get; set; }
        public int? RegisterItemId { get; set; }
        public int? CustomRegisterId { get; set; }
        public int? CustomRegisterItemId { get; set; }
        public string CrTextValue { get; set; }

        [ConcurrencyCheck]
        public int? OptimisticLockField { get; set; }

        public virtual CustomRegister CustomRegister { get; set; }
        public virtual CustomRegisterItem CustomRegisterItem { get; set; }

        public CustomRegisterValue()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>

