// <auto-generated>
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using cpModel.Interfaces;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading;
using System.Threading.Tasks;

namespace cpModel.Models
{
    public partial class DayCost: ITrackableEntity, IReplicableEntity, ILockableEntity
    {
        public Guid? UniqueId { get; set; }
        public string HrId { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public bool? IsSoftDeleted { get; set; }
        public int DayCostId { get; set; }
        public int? ReportPeriodId { get; set; }
        public DateTime? DateCost { get; set; }
        public int? SupplierObjId { get; set; }
        public int? ResourceObjId { get; set; }
        public int? ResType { get; set; }
        public int? CostCodeId { get; set; }
        public decimal? Qty { get; set; }
        public string Unit { get; set; }
        public decimal? Rate { get; set; }
        public string DocketRef { get; set; }
        public string Notes { get; set; }
        public int? ProjectId { get; set; }
        public int? InvoiceId { get; set; }
        public string Supplier { get; set; }
        public string Resource { get; set; }
        public bool? IsHidden { get; set; }
        public bool? NoAccrual { get; set; }
        public bool? IsCorrection { get; set; }
        public bool? NotInvoiced { get; set; }
        public int? ReceiptId { get; set; }
        public int? ReceiptDetailId { get; set; }
        public int? SiteDiaryCostId { get; set; }

        [ConcurrencyCheck]
        public int? OptimisticLockField { get; set; }

        // Reverse navigation
        public virtual ICollection<DaycostCostCode> DaycostCostCodes { get; set; }
        public virtual ICollection<DaycostCustomRegItem> DaycostCustomRegItems { get; set; }

        public virtual CostCode CostCode { get; set; }
        public virtual Invoice Invoice { get; set; }
        public virtual Project Project { get; set; }
        public virtual Receipt Receipt { get; set; }
        public virtual ReceiptDetail ReceiptDetail { get; set; }
        public virtual ReportPeriod ReportPeriod { get; set; }
        public virtual Resource ResourceObj { get; set; }
        public virtual SiteDiaryCost SiteDiaryCost { get; set; }
        public virtual Supplier SupplierObj { get; set; }

        public DayCost()
        {
            DaycostCostCodes = new HashSet<DaycostCostCode>();
            DaycostCustomRegItems = new HashSet<DaycostCustomRegItem>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>

