// <auto-generated>
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using cpModel.Interfaces;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading;
using System.Threading.Tasks;

namespace cpModel.Models
{
    public partial class ExternalApi: ITrackableEntity, IReplicableEntity, ILockableEntity
    {
        public Guid? UniqueId { get; set; }
        public string HrId { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public bool? IsSoftDeleted { get; set; }
        public int ExternalApiId { get; set; }
        public string ApiUrl { get; set; }
        public int? ApiTypeId { get; set; }
        public DateTime? ExpiryDate { get; set; }
        public string ApiData { get; set; }

        [ConcurrencyCheck]
        public int? OptimisticLockField { get; set; }

        // Reverse navigation
        public virtual ICollection<User> Users { get; set; }

        public ExternalApi()
        {
            Users = new HashSet<User>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>

