// <auto-generated>
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using cpModel.Interfaces;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading;
using System.Threading.Tasks;

namespace cpModel.Models
{
    public partial class LotItpTest: ITrackableEntity, IReplicableEntity, ILockableEntity
    {
        public Guid? UniqueId { get; set; }
        public string HrId { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public bool? IsSoftDeleted { get; set; }
        public int LotItpTestId { get; set; }
        public int? LotItpDetailId { get; set; }
        public int? TestMethodId { get; set; }
        public decimal? FreqNorm { get; set; }
        public decimal? FreqRed { get; set; }
        public decimal? FreqLotNorm { get; set; }
        public decimal? FreqLotRed { get; set; }
        public string Unit { get; set; }
        public int? QuantityBasis { get; set; }
        public string Compliance { get; set; }
        public int? TestStatus { get; set; }
        public int? OrSet { get; set; }
        public string Comment { get; set; }
        public bool? IsOptional { get; set; }
        public bool? IsDefault { get; set; }

        [ConcurrencyCheck]
        public int? OptimisticLockField { get; set; }

        public virtual LotItpDetail LotItpDetail { get; set; }
        public virtual TestMethod TestMethod { get; set; }

        public LotItpTest()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>

