// <auto-generated>
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using cpModel.Interfaces;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading;
using System.Threading.Tasks;

namespace cpModel.Models
{
    public partial class LotQuantity: ITrackableEntity, IReplicableEntity, ILockableEntity
    {
        public Guid? UniqueId { get; set; }
        public string HrId { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public bool? IsSoftDeleted { get; set; }
        public int QuantityId { get; set; }
        public int? LotId { get; set; }
        public int? ScheduleId { get; set; }
        public string Description { get; set; }
        public decimal? Qty { get; set; }
        public string Unit { get; set; }
        public int? NcrId { get; set; }
        public bool? NonClaimable { get; set; }
        public int? ManagedById { get; set; }
        public DateTime? PublishedDate { get; set; }
        public DateTime? AdjDate { get; set; }
        public decimal? PercComp { get; set; }
        public bool? Preliminary { get; set; }
        public decimal? ReducedPayment { get; set; }
        public int? VariationId { get; set; }
        public string Comments { get; set; }
        public decimal? AlternateQty { get; set; }
        public int? ApprovedById { get; set; }
        public DateTime? ApprovalDate { get; set; }
        public string ApprovalComment { get; set; }
        public int? Status { get; set; }

        [ConcurrencyCheck]
        public int? OptimisticLockField { get; set; }

        // Reverse navigation
        public virtual ICollection<Approval> Approvals { get; set; }
        public virtual ICollection<ApprovalLotQty> ApprovalLotQties { get; set; }
        public virtual ICollection<FsLotQty> FsLotQties { get; set; }
        public virtual ICollection<LotItpQty> LotItpQties { get; set; }
        public virtual ICollection<ProgressClaimSnapshot> ProgressClaimSnapshots { get; set; }
        public virtual ICollection<QtyCustomRegItem> QtyCustomRegItems { get; set; }

        public virtual Lot Lot { get; set; }
        public virtual LotQtyStatus LotQtyStatus { get; set; }
        public virtual Ncr Ncr { get; set; }
        public virtual ScheduleItem ScheduleItem { get; set; }
        public virtual User ApprovedBy { get; set; }
        public virtual User ManagedBy { get; set; }
        public virtual Variation Variation { get; set; }

        public LotQuantity()
        {
            Approvals = new HashSet<Approval>();
            ApprovalLotQties = new HashSet<ApprovalLotQty>();
            FsLotQties = new HashSet<FsLotQty>();
            LotItpQties = new HashSet<LotItpQty>();
            ProgressClaimSnapshots = new HashSet<ProgressClaimSnapshot>();
            QtyCustomRegItems = new HashSet<QtyCustomRegItem>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>

