// <auto-generated>
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using cpModel.Interfaces;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading;
using System.Threading.Tasks;

namespace cpModel.Models
{
    public partial class LotRelation: ITrackableEntity, IReplicableEntity, ILockableEntity
    {
        public Guid? UniqueId { get; set; }
        public string HrId { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public bool? IsSoftDeleted { get; set; }
        public int? LotId1 { get; set; }
        public int? RelationshipType { get; set; }
        public int RelLotId { get; set; }
        public int? LotId2 { get; set; }
        public string Description { get; set; }

        [ConcurrencyCheck]
        public int? OptimisticLockField { get; set; }

        public virtual Lot Lot1 { get; set; }
        public virtual Lot Lot2 { get; set; }

        public LotRelation()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>

