// <auto-generated>
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using cpModel.Interfaces;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading;
using System.Threading.Tasks;

namespace cpModel.Models
{
    public partial class NcrRevision: ITrackableEntity, IReplicableEntity, ILockableEntity
    {
        public Guid? UniqueId { get; set; }
        public string HrId { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public bool? IsSoftDeleted { get; set; }
        public int NcrRevisionId { get; set; }
        public int? NcrId { get; set; }
        public string NcrRef { get; set; }
        public string RevisionInfo { get; set; }
        public DateTime? RevisionDate { get; set; }
        public int? RevisionById { get; set; }

        [ConcurrencyCheck]
        public int? OptimisticLockField { get; set; }

        public virtual Ncr Ncr { get; set; }
        public virtual User User { get; set; }

        public NcrRevision()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>

