// <auto-generated>
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using cpModel.Interfaces;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading;
using System.Threading.Tasks;

namespace cpModel.Models
{
    public partial class NotificationTo: ITrackableEntity, IReplicableEntity, ILockableEntity
    {
        public Guid? UniqueId { get; set; }
        public string HrId { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public bool? IsSoftDeleted { get; set; }
        public int NotificationToId { get; set; }
        public int? NotificationId { get; set; }
        public int? UserId { get; set; }
        public int? NotificationTypeId { get; set; }
        public DateTime? DateRead { get; set; }
        public DateTime? DateDismissed { get; set; }
        public int? PriorityId { get; set; }
        public string DismissalReason { get; set; }
        public DateTime? DatePollNotification { get; set; }

        [ConcurrencyCheck]
        public int? OptimisticLockField { get; set; }

        public virtual Notification Notification { get; set; }
        public virtual User User { get; set; }

        public NotificationTo()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>

