// <auto-generated>
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using cpModel.Interfaces;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading;
using System.Threading.Tasks;

namespace cpModel.Models
{
    public partial class Notification: ITrackableEntity, IReplicableEntity, ILockableEntity
    {
        public Guid? UniqueId { get; set; }
        public string HrId { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public bool? IsSoftDeleted { get; set; }
        public int NotificationId { get; set; }
        public int? NotificationNo { get; set; }
        public DateTime? NoticeDate { get; set; }
        public int? NoticeById { get; set; }
        public int? ProjectId { get; set; }
        public string SubjectText { get; set; }
        public string ContentHtml { get; set; }
        public DateTime? DateRequiredBy { get; set; }
        public int? RegisterId { get; set; }
        public DateTime? PublishDate { get; set; }
        public DateTime? ActionDate { get; set; }
        public int? ActionById { get; set; }
        public string ActionComment { get; set; }

        [ConcurrencyCheck]
        public int? OptimisticLockField { get; set; }

        // Reverse navigation
        public virtual ICollection<FsNotification> FsNotifications { get; set; }
        public virtual ICollection<NotificationEmail> NotificationEmails { get; set; }
        public virtual ICollection<NotificationItem> NotificationItems { get; set; }
        public virtual ICollection<NotificationTo> NotificationTos { get; set; }

        public virtual Project Project { get; set; }
        public virtual User ActionBy { get; set; }
        public virtual User NoticeBy { get; set; }

        public Notification()
        {
            FsNotifications = new HashSet<FsNotification>();
            NotificationEmails = new HashSet<NotificationEmail>();
            NotificationItems = new HashSet<NotificationItem>();
            NotificationTos = new HashSet<NotificationTo>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>

