// <auto-generated>
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using cpModel.Interfaces;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading;
using System.Threading.Tasks;

namespace cpModel.Models
{
    public partial class PhotoPunchListItem: ITrackableEntity, IReplicableEntity, ILockableEntity
    {
        public Guid? UniqueId { get; set; }
        public string HrId { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public bool? IsSoftDeleted { get; set; }
        public int PhotoPunchListItemId { get; set; }
        public int? PhotoId { get; set; }
        public int? PunchListItemId { get; set; }
        public int? PunchListItemPointId { get; set; }
        public decimal? OrderId { get; set; }

        [ConcurrencyCheck]
        public int? OptimisticLockField { get; set; }

        public virtual Photo Photo { get; set; }
        public virtual PunchlistItem PunchlistItem { get; set; }
        public virtual PunchlistItemPoint PunchlistItemPoint { get; set; }

        public PhotoPunchListItem()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>

