// <auto-generated>
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using cpModel.Interfaces;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading;
using System.Threading.Tasks;

namespace cpModel.Models
{
    public partial class Production: ITrackableEntity, IReplicableEntity, ILockableEntity
    {
        public Guid? UniqueId { get; set; }
        public string HrId { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public bool? IsSoftDeleted { get; set; }
        public int ProductionId { get; set; }
        public int? ReportPeriodId { get; set; }
        public DateTime? DateProduction { get; set; }
        public int? CostCodeId { get; set; }
        public decimal? Qty { get; set; }
        public string Unit { get; set; }
        public decimal? Total { get; set; }
        public decimal? Budget { get; set; }
        public string Notes { get; set; }
        public int? ProjectId { get; set; }

        [ConcurrencyCheck]
        public int? OptimisticLockField { get; set; }

        public virtual CostCode CostCode { get; set; }
        public virtual Project Project { get; set; }
        public virtual ReportPeriod ReportPeriod { get; set; }

        public Production()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>

