// <auto-generated>
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using cpModel.Interfaces;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading;
using System.Threading.Tasks;

namespace cpModel.Models
{
    public partial class PunchlistItemPoint: ITrackableEntity, IReplicableEntity, ILockableEntity
    {
        public Guid? UniqueId { get; set; }
        public string HrId { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public bool? IsSoftDeleted { get; set; }
        public int PunchListItemPointId { get; set; }
        public int? PunchlistItemId { get; set; }
        public decimal? X { get; set; }
        public decimal? Y { get; set; }
        public decimal? Z { get; set; }
        public int? ReferenceId { get; set; }
        public int? ControlLineId { get; set; }
        public string Comment { get; set; }

        [ConcurrencyCheck]
        public int? OptimisticLockField { get; set; }

        // Reverse navigation
        public virtual ICollection<FsPunchlistItem> FsPunchlistItems { get; set; }
        public virtual ICollection<PhotoPunchListItem> PhotoPunchListItems { get; set; }

        public virtual ControlLine ControlLine { get; set; }
        public virtual PunchlistItem PunchlistItem { get; set; }

        public PunchlistItemPoint()
        {
            FsPunchlistItems = new HashSet<FsPunchlistItem>();
            PhotoPunchListItems = new HashSet<PhotoPunchListItem>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>

