// <auto-generated>
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using cpModel.Interfaces;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading;
using System.Threading.Tasks;

namespace cpModel.Models
{
    public partial class PurchaseOrderDetail: ITrackableEntity, IReplicableEntity, ILockableEntity
    {
        public Guid? UniqueId { get; set; }
        public string HrId { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public bool? IsSoftDeleted { get; set; }
        public int PoDetailId { get; set; }
        public int? PurchaseOrderId { get; set; }
        public decimal? ItemNumber { get; set; }
        public string ItemDescription { get; set; }
        public bool? IsRateOnly { get; set; }
        public decimal? Qty { get; set; }
        public string Unit { get; set; }
        public decimal? Rate { get; set; }
        public string Notes { get; set; }
        public decimal? GstRate { get; set; }
        public int? ResType { get; set; }
        public int? CostCodeId { get; set; }

        [ConcurrencyCheck]
        public int? OptimisticLockField { get; set; }

        // Reverse navigation
        public virtual ICollection<ReceiptDetail> ReceiptDetails { get; set; }
        public virtual ICollection<Resource> Resources { get; set; }

        public virtual CostCode CostCode { get; set; }
        public virtual PurchaseOrder PurchaseOrder { get; set; }

        public PurchaseOrderDetail()
        {
            ReceiptDetails = new HashSet<ReceiptDetail>();
            Resources = new HashSet<Resource>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>

