// <auto-generated>
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using cpModel.Interfaces;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading;
using System.Threading.Tasks;

namespace cpModel.Models
{
    public partial class Resource: ITrackableEntity, IReplicableEntity, ILockableEntity
    {
        public Guid? UniqueId { get; set; }
        public string HrId { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public bool? IsSoftDeleted { get; set; }
        public int ResourceId { get; set; }
        public int? SupplierId { get; set; }
        public string ResourceName { get; set; }
        public decimal? Rate { get; set; }
        public string Unit { get; set; }
        public int? ResType { get; set; }
        public int? ProjectId { get; set; }
        public bool? IsHidden { get; set; }
        public bool? NotInvoiced { get; set; }
        public int? PurchaseOrderDetailId { get; set; }

        [ConcurrencyCheck]
        public int? OptimisticLockField { get; set; }

        // Reverse navigation
        public virtual ICollection<DayCost> DayCosts { get; set; }
        public virtual ICollection<SiteDiaryCost> SiteDiaryCosts { get; set; }

        public virtual Project Project { get; set; }
        public virtual PurchaseOrderDetail PurchaseOrderDetail { get; set; }
        public virtual Supplier Supplier { get; set; }

        public Resource()
        {
            DayCosts = new HashSet<DayCost>();
            SiteDiaryCosts = new HashSet<SiteDiaryCost>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>

