// <auto-generated>
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using cpModel.Interfaces;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading;
using System.Threading.Tasks;

namespace cpModel.Models
{
    public partial class Revision: ITrackableEntity, IReplicableEntity, ILockableEntity
    {
        public Guid? UniqueId { get; set; }
        public string HrId { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public bool? IsSoftDeleted { get; set; }
        public int RevisionId { get; set; }
        public int? DocumentId { get; set; }
        public string Description { get; set; }
        public string RevRef { get; set; }
        public DateTime? RevisionDate { get; set; }
        public DateTime? DateReceived { get; set; }
        public string EntityRevised { get; set; }

        [ConcurrencyCheck]
        public int? OptimisticLockField { get; set; }

        // Reverse navigation
        public virtual ICollection<FsDoc> FsDocs { get; set; }
        public virtual ICollection<TransmittalItem> TransmittalItems { get; set; }

        public virtual CpDocument CpDocument { get; set; }

        public Revision()
        {
            FsDocs = new HashSet<FsDoc>();
            TransmittalItems = new HashSet<TransmittalItem>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>

