// <auto-generated>
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using cpModel.Interfaces;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading;
using System.Threading.Tasks;

namespace cpModel.Models
{
    public partial class RiskActivityStep: ITrackableEntity, IReplicableEntity, ILockableEntity
    {
        public Guid? UniqueId { get; set; }
        public string HrId { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public bool? IsSoftDeleted { get; set; }
        public int RiskActivityStepId { get; set; }
        public int? RiskActivityId { get; set; }
        public decimal? OrderId { get; set; }
        public string StepDescription { get; set; }

        [ConcurrencyCheck]
        public int? OptimisticLockField { get; set; }

        // Reverse navigation
        public virtual ICollection<RiskHazard> RiskHazards { get; set; }

        public virtual RiskActivity RiskActivity { get; set; }

        public RiskActivityStep()
        {
            RiskHazards = new HashSet<RiskHazard>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>

