// <auto-generated>
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using cpModel.Interfaces;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading;
using System.Threading.Tasks;

namespace cpModel.Models
{
    public partial class SiteDiaryCostCode: ITrackableEntity, IReplicableEntity, ILockableEntity
    {
        public Guid? UniqueId { get; set; }
        public string HrId { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public bool? IsSoftDeleted { get; set; }
        public int SiteDiaryCostCodeId { get; set; }
        public int? SiteDiaryCostId { get; set; }
        public int? CostCodeId { get; set; }
        public decimal? Qty { get; set; }

        [ConcurrencyCheck]
        public int? OptimisticLockField { get; set; }

        public virtual CostCode CostCode { get; set; }
        public virtual SiteDiaryCost SiteDiaryCost { get; set; }

        public SiteDiaryCostCode()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>

