// <auto-generated>
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using cpModel.Interfaces;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading;
using System.Threading.Tasks;

namespace cpModel.Models
{
    public partial class SiteDiaryCost: ITrackableEntity, IReplicableEntity, ILockableEntity
    {
        public Guid? UniqueId { get; set; }
        public string HrId { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public bool? IsSoftDeleted { get; set; }
        public int SiteDiaryCostId { get; set; }
        public int? SiteDiaryId { get; set; }
        public int? SupplierId { get; set; }
        public string ResourceName { get; set; }
        public int? ResourceId { get; set; }
        public int? ResourceTypeId { get; set; }
        public decimal? Qty { get; set; }
        public string Unit { get; set; }
        public decimal? Rate { get; set; }
        public string Notes { get; set; }
        public string DocketRef { get; set; }

        [ConcurrencyCheck]
        public int? OptimisticLockField { get; set; }

        // Reverse navigation
        public virtual ICollection<DayCost> DayCosts { get; set; }
        public virtual ICollection<SiteDiaryCostCode> SiteDiaryCostCodes { get; set; }

        public virtual Resource Resource { get; set; }
        public virtual SiteDiary SiteDiary { get; set; }
        public virtual Supplier Supplier { get; set; }

        public SiteDiaryCost()
        {
            DayCosts = new HashSet<DayCost>();
            SiteDiaryCostCodes = new HashSet<SiteDiaryCostCode>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>

