// <auto-generated>
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using cpModel.Interfaces;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading;
using System.Threading.Tasks;

namespace cpModel.Models
{
    public partial class SurveyChainage: ITrackableEntity, IReplicableEntity, ILockableEntity
    {
        public Guid? UniqueId { get; set; }
        public string HrId { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public bool? IsSoftDeleted { get; set; }
        public int SurveyChainageId { get; set; }
        public int? SurveyId { get; set; }
        public decimal? OrderId { get; set; }
        public int? ControlLineId { get; set; }
        public int? PositionTypeId { get; set; }
        public decimal? Chainage { get; set; }
        public decimal? LeftOs { get; set; }
        public decimal? RightOs { get; set; }
        public decimal? Rl { get; set; }
        public bool? IsApproximate { get; set; }

        [ConcurrencyCheck]
        public int? OptimisticLockField { get; set; }

        public virtual ControlLine ControlLine { get; set; }
        public virtual SurveyRequest SurveyRequest { get; set; }

        public SurveyChainage()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>

