// <auto-generated>
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using cpModel.Interfaces;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading;
using System.Threading.Tasks;

namespace cpModel.Models
{
    public partial class SystemControl
    {
        public int SystemControlId { get; set; }
        public string Key { get; set; }
        public string Value { get; set; }

        public SystemControl()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>

