// <auto-generated>
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using cpModel.Interfaces;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading;
using System.Threading.Tasks;

namespace cpModel.Models
{
    public partial class TestMethod: ITrackableEntity, IReplicableEntity, ILockableEntity
    {
        public Guid? UniqueId { get; set; }
        public string HrId { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public bool? IsSoftDeleted { get; set; }
        public int TestMethodId { get; set; }
        public string TestNum { get; set; }
        public int? ProjectId { get; set; }
        public string TestDescription { get; set; }
        public decimal? TestCost { get; set; }
        public decimal? TestRev { get; set; }
        public decimal? EstTurnaround { get; set; }

        [ConcurrencyCheck]
        public int? OptimisticLockField { get; set; }

        // Reverse navigation
        public virtual ICollection<ItpTesting> ItpTestings { get; set; }
        public virtual ICollection<LotItpTest> LotItpTests { get; set; }
        public virtual ICollection<TestRequestTest> TestRequestTests { get; set; }
        public virtual ICollection<TestResultField> TestResultFields { get; set; }

        public virtual Project Project { get; set; }

        public TestMethod()
        {
            ItpTestings = new HashSet<ItpTesting>();
            LotItpTests = new HashSet<LotItpTest>();
            TestRequestTests = new HashSet<TestRequestTest>();
            TestResultFields = new HashSet<TestResultField>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>

