// <auto-generated>
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using cpModel.Interfaces;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading;
using System.Threading.Tasks;

namespace cpModel.Models
{
    public partial class WorkflowLog: ITrackableEntity, IReplicableEntity, ILockableEntity
    {
        public Guid? UniqueId { get; set; }
        public string HrId { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public bool? IsSoftDeleted { get; set; }
        public int WorkflowLogId { get; set; }
        public int? WorkflowId { get; set; }
        public int? WorkflowActionId { get; set; }
        public int? WorkflowStepId { get; set; }
        public int? UserId { get; set; }
        public DateTime? LogDate { get; set; }
        public string LogCommentHtml { get; set; }
        public bool? IsPrivate { get; set; }

        [ConcurrencyCheck]
        public int? OptimisticLockField { get; set; }

        // Reverse navigation
        public virtual ICollection<ApprovalEmail> ApprovalEmails { get; set; }
        public virtual ICollection<FsWorkflowLog> FsWorkflowLogs { get; set; }

        public virtual User User { get; set; }
        public virtual Workflow Workflow { get; set; }
        public virtual WorkflowAction WorkflowAction { get; set; }
        public virtual WorkflowStep WorkflowStep { get; set; }

        public WorkflowLog()
        {
            ApprovalEmails = new HashSet<ApprovalEmail>();
            FsWorkflowLogs = new HashSet<FsWorkflowLog>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>

