//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cpReportDefinitions.FieldRep {
    
    public partial class rptIncident : rptTemplate {
        private void InitializeComponent() {
            DevExpress.XtraReports.ReportInitializer reportInitializer = new DevExpress.XtraReports.ReportInitializer(this, "cpReportDefinitions.FieldRep.rptIncident.repx");

            // Controls
            this.Detail = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("Detail");
            this.PageHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.PageHeaderBand>("PageHeader");
            this.PageFooter = reportInitializer.GetControl<DevExpress.XtraReports.UI.PageFooterBand>("PageFooter");
            this.DetailReport = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailReportBand>("DetailReport");
            this.TopMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.TopMarginBand>("TopMargin");
            this.BottomMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.BottomMarginBand>("BottomMargin");
            this.dummyMid = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailReportBand>("dummyMid");
            this.pnlTop = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPanel>("pnlTop");
            this.xrLabel25 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel25");
            this.xrLabel24 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel24");
            this.xrLabel23 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel23");
            this.xrCheckBox2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("xrCheckBox2");
            this.xrLabel22 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel22");
            this.xrLabel21 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel21");
            this.xrLabel20 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel20");
            this.xrLabel19 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel19");
            this.xrLabel18 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel18");
            this.xrLabel17 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel17");
            this.xrLabel16 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel16");
            this.xrLabel15 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel15");
            this.xrLabel14 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel14");
            this.xrLabel13 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel13");
            this.xrLabel12 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel12");
            this.xrLabel11 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel11");
            this.xrLabel5 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel5");
            this.xrLabel3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel3");
            this.xrLabel1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel1");
            this.xrLabel2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel2");
            this.headPanel = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPanel>("headPanel");
            this.lbReportHeading = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbReportHeading");
            this.lbProject = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbProject");
            this.lbRecordReference = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbRecordReference");
            this.pbLogo = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPictureBox>("pbLogo");
            this.lbFooterText = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbFooterText");
            this.xrPageInfo1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPageInfo>("xrPageInfo1");
            this.Detail1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("Detail1");
            this.ReportHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportHeaderBand>("ReportHeader");
            this.xrLabel7 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel7");
            this.xrCheckBox1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("xrCheckBox1");
            this.xrLabel6 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel6");
            this.xrLabel10 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel10");
            this.xrLabel9 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel9");
            this.xrLabel8 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel8");
            this.xrLabel4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel4");
            this.Detail3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("Detail3");
            this.dummyMidHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportHeaderBand>("dummyMidHeader");
            this.xrLabel30 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel30");
            this.reReoccurrence = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("reReoccurrence");
            this.reActions = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("reActions");
            this.xrLabel29 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel29");
            this.xrLabel28 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel28");
            this.xrLabel27 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel27");
            this.reCause = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("reCause");
            this.reDescription = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("reDescription");
            this.xrCheckBox3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("xrCheckBox3");
            this.xrLabel26 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel26");
            this.sbApproval = reportInitializer.GetControl<DevExpress.XtraReports.UI.SubBand>("sbApproval");
            this.sbCloseout = reportInitializer.GetControl<DevExpress.XtraReports.UI.SubBand>("sbCloseout");
            this.xrPanel1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPanel>("xrPanel1");
            this.reApproval = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("reApproval");
            this.xrLabel34 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel34");
            this.xrLabel33 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel33");
            this.xrLabel32 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel32");
            this.xrLabel31 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel31");
            this.xrLabel39 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel39");
            this.xrPanel2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPanel>("xrPanel2");
            this.xrLabel40 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel40");
            this.xrLabel38 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel38");
            this.xrLabel37 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel37");
            this.xrLabel36 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel36");
            this.xrLabel35 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel35");
            this.reCloseout = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("reCloseout");

            // Data Sources
            this.objectDataSource1 = reportInitializer.GetDataSource<DevExpress.DataAccess.ObjectBinding.ObjectDataSource>("objectDataSource1");
            this.objectDataSource1.DataSource = typeof(cpModel.Dtos.Report.IncidentReportDto);

            // Styles
            this.Title = reportInitializer.GetStyle("Title");
            this.FieldCaption = reportInitializer.GetStyle("FieldCaption");
            this.PageInfo = reportInitializer.GetStyle("PageInfo");
            this.DataField = reportInitializer.GetStyle("DataField");
        }
        private DevExpress.XtraReports.UI.DetailBand Detail;
        private DevExpress.XtraReports.UI.PageHeaderBand PageHeader;
        private DevExpress.XtraReports.UI.PageFooterBand PageFooter;
        private DevExpress.XtraReports.UI.DetailReportBand DetailReport;
        private DevExpress.XtraReports.UI.TopMarginBand TopMargin;
        private DevExpress.XtraReports.UI.BottomMarginBand BottomMargin;
        private DevExpress.XtraReports.UI.DetailReportBand dummyMid;
        private DevExpress.XtraReports.UI.XRPanel pnlTop;
        private DevExpress.XtraReports.UI.XRLabel xrLabel25;
        private DevExpress.XtraReports.UI.XRLabel xrLabel24;
        private DevExpress.XtraReports.UI.XRLabel xrLabel23;
        private DevExpress.XtraReports.UI.XRCheckBox xrCheckBox2;
        private DevExpress.XtraReports.UI.XRLabel xrLabel22;
        private DevExpress.XtraReports.UI.XRLabel xrLabel21;
        private DevExpress.XtraReports.UI.XRLabel xrLabel20;
        private DevExpress.XtraReports.UI.XRLabel xrLabel19;
        private DevExpress.XtraReports.UI.XRLabel xrLabel18;
        private DevExpress.XtraReports.UI.XRLabel xrLabel17;
        private DevExpress.XtraReports.UI.XRLabel xrLabel16;
        private DevExpress.XtraReports.UI.XRLabel xrLabel15;
        private DevExpress.XtraReports.UI.XRLabel xrLabel14;
        private DevExpress.XtraReports.UI.XRLabel xrLabel13;
        private DevExpress.XtraReports.UI.XRLabel xrLabel12;
        private DevExpress.XtraReports.UI.XRLabel xrLabel11;
        private DevExpress.XtraReports.UI.XRLabel xrLabel5;
        private DevExpress.XtraReports.UI.XRLabel xrLabel3;
        private DevExpress.XtraReports.UI.XRLabel xrLabel1;
        private DevExpress.XtraReports.UI.XRLabel xrLabel2;
        private DevExpress.XtraReports.UI.XRPanel headPanel;
        private DevExpress.XtraReports.UI.XRLabel lbReportHeading;
        private DevExpress.XtraReports.UI.XRLabel lbProject;
        private DevExpress.XtraReports.UI.XRLabel lbRecordReference;
        private DevExpress.XtraReports.UI.XRPictureBox pbLogo;
        private DevExpress.XtraReports.UI.XRLabel lbFooterText;
        private DevExpress.XtraReports.UI.XRPageInfo xrPageInfo1;
        private DevExpress.XtraReports.UI.DetailBand Detail1;
        private DevExpress.XtraReports.UI.ReportHeaderBand ReportHeader;
        private DevExpress.XtraReports.UI.XRLabel xrLabel7;
        private DevExpress.XtraReports.UI.XRCheckBox xrCheckBox1;
        private DevExpress.XtraReports.UI.XRLabel xrLabel6;
        private DevExpress.XtraReports.UI.XRLabel xrLabel10;
        private DevExpress.XtraReports.UI.XRLabel xrLabel9;
        private DevExpress.XtraReports.UI.XRLabel xrLabel8;
        private DevExpress.XtraReports.UI.XRLabel xrLabel4;
        private DevExpress.DataAccess.ObjectBinding.ObjectDataSource objectDataSource1;
        private DevExpress.XtraReports.UI.DetailBand Detail3;
        private DevExpress.XtraReports.UI.ReportHeaderBand dummyMidHeader;
        private DevExpress.XtraReports.UI.XRLabel xrLabel30;
        private DevExpress.XtraReports.UI.XRRichText reReoccurrence;
        private DevExpress.XtraReports.UI.XRRichText reActions;
        private DevExpress.XtraReports.UI.XRLabel xrLabel29;
        private DevExpress.XtraReports.UI.XRLabel xrLabel28;
        private DevExpress.XtraReports.UI.XRLabel xrLabel27;
        private DevExpress.XtraReports.UI.XRRichText reCause;
        private DevExpress.XtraReports.UI.XRRichText reDescription;
        private DevExpress.XtraReports.UI.XRCheckBox xrCheckBox3;
        private DevExpress.XtraReports.UI.XRLabel xrLabel26;
        private DevExpress.XtraReports.UI.SubBand sbApproval;
        private DevExpress.XtraReports.UI.SubBand sbCloseout;
        private DevExpress.XtraReports.UI.XRPanel xrPanel1;
        private DevExpress.XtraReports.UI.XRRichText reApproval;
        private DevExpress.XtraReports.UI.XRLabel xrLabel34;
        private DevExpress.XtraReports.UI.XRLabel xrLabel33;
        private DevExpress.XtraReports.UI.XRLabel xrLabel32;
        private DevExpress.XtraReports.UI.XRLabel xrLabel31;
        private DevExpress.XtraReports.UI.XRLabel xrLabel39;
        private DevExpress.XtraReports.UI.XRPanel xrPanel2;
        private DevExpress.XtraReports.UI.XRLabel xrLabel40;
        private DevExpress.XtraReports.UI.XRLabel xrLabel38;
        private DevExpress.XtraReports.UI.XRLabel xrLabel37;
        private DevExpress.XtraReports.UI.XRLabel xrLabel36;
        private DevExpress.XtraReports.UI.XRLabel xrLabel35;
        private DevExpress.XtraReports.UI.XRRichText reCloseout;
        private DevExpress.XtraReports.UI.XRControlStyle Title;
        private DevExpress.XtraReports.UI.XRControlStyle FieldCaption;
        private DevExpress.XtraReports.UI.XRControlStyle PageInfo;
        private DevExpress.XtraReports.UI.XRControlStyle DataField;
    }
}
