// <auto-generated>
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using cpModel.Interfaces;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading;
using System.Threading.Tasks;

namespace cpModel.Dtos
{
    public class TransmittalItemDto
    {
        public int TransmittalItemId { get; set; }
        public int? TransmittalId { get; set; }
        public int? RevisionId { get; set; }
        public int? DocumentId { get; set; }
        public int? Qty { get; set; }

        public string DocumentNo { get; set; }
        public string DocumentDesc { get; set; }
        public string RevisionName { get; set; }
    }

}
// </auto-generated>

