//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cpReportDefinitions.ConformanceRep {
    
    public partial class rptChecklist : rptTemplate {
        private void InitializeComponent() {
            DevExpress.XtraReports.ReportInitializer reportInitializer = new DevExpress.XtraReports.ReportInitializer(this, "cpReportDefinitions.ConformanceRep.rptChecklist.repx");

            // Controls
            this.Detail = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("Detail");
            this.PageHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.PageHeaderBand>("PageHeader");
            this.PageFooter = reportInitializer.GetControl<DevExpress.XtraReports.UI.PageFooterBand>("PageFooter");
            this.ITPDetail = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailReportBand>("ITPDetail");
            this.TopMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.TopMarginBand>("TopMargin");
            this.BottomMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.BottomMarginBand>("BottomMargin");
            this.headPanel = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPanel>("headPanel");
            this.lbReportHeading = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbReportHeading");
            this.lbProject = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbProject");
            this.lbRecordReference = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbRecordReference");
            this.pbLogo = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPictureBox>("pbLogo");
            this.lbFooterText = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbFooterText");
            this.xrPageInfo1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPageInfo>("xrPageInfo1");
            this.lblFtrCenterText = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lblFtrCenterText");
            this.LotItpDetail_Detail = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("LotItpDetail_Detail");
            this.ITPTest = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailReportBand>("ITPTest");
            this.ReportFooter = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportFooterBand>("ReportFooter");
            this.GroupHeader1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.GroupHeaderBand>("GroupHeader1");
            this.pbGroupFooter = reportInitializer.GetControl<DevExpress.XtraReports.UI.GroupFooterBand>("pbGroupFooter");
            this.bxNCR = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRShape>("bxNCR");
            this.bxVerified = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRShape>("bxVerified");
            this.bxApproved = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRShape>("bxApproved");
            this.bxChecked = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRShape>("bxChecked");
            this.xrrtDescription = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrrtDescription");
            this.lbIndex = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbIndex");
            this.ITPTest_Detail = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("ITPTest_Detail");
            this.lbTest = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbTest");
            this.xrLabel1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel1");
            this.xrrtCompliance = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrrtCompliance");
            this.lblFreq = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lblFreq");
            this.sbFullHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.SubBand>("sbFullHeader");
            this.sbShortHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.SubBand>("sbShortHeader");
            this.pnlHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPanel>("pnlHeader");
            this.xrLabel6 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel6");
            this.lblLot = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lblLot");
            this.lblDateComp = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lblDateComp");
            this.lblDateCompHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lblDateCompHeader");
            this.lblDateOpenHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lblDateOpenHeader");
            this.lblDateOpen = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lblDateOpen");
            this.lblDateWorkStHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lblDateWorkStHeader");
            this.lblDateWorkSt = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lblDateWorkSt");
            this.lbCheck = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbCheck");
            this.lbVerify = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbVerify");
            this.lbAppr = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbAppr");
            this.lbNCR = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbNCR");
            this.sbQtyData = reportInitializer.GetControl<DevExpress.XtraReports.UI.SubBand>("sbQtyData");
            this.sbComment = reportInitializer.GetControl<DevExpress.XtraReports.UI.SubBand>("sbComment");
            this.sbShowSig = reportInitializer.GetControl<DevExpress.XtraReports.UI.SubBand>("sbShowSig");
            this.pnlQty = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPanel>("pnlQty");
            this.pnlComment = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPanel>("pnlComment");
            this.pnlHeadings = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPanel>("pnlHeadings");
            this.pnlRespOficer = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPanel>("pnlRespOficer");
            this.pnlVerAuth = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPanel>("pnlVerAuth");
            this.xrLabel8 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel8");
            this.xrLabel9 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel9");
            this.xrLine6 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLine>("xrLine6");
            this.lbRespOffice = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbRespOffice");
            this.xrLine7 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLine>("xrLine7");
            this.xrLine8 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLine>("xrLine8");
            this.xrLabel7 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel7");
            this.xrLine4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLine>("xrLine4");
            this.xrLabel2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel2");
            this.xrLine3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLine>("xrLine3");
            this.xrLine5 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLine>("xrLine5");
            this.xrLabel5 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel5");

            // Data Sources
            this.objectDataSource1 = reportInitializer.GetDataSource<DevExpress.DataAccess.ObjectBinding.ObjectDataSource>("objectDataSource1");
            this.objectDataSource1.DataSource = typeof(cpModel.Dtos.Report.IItpReportDto);

            // Styles
            this.Title = reportInitializer.GetStyle("Title");
            this.FieldCaption = reportInitializer.GetStyle("FieldCaption");
            this.PageInfo = reportInitializer.GetStyle("PageInfo");
            this.DataField = reportInitializer.GetStyle("DataField");
        }
        private DevExpress.XtraReports.UI.DetailBand Detail;
        private DevExpress.XtraReports.UI.PageHeaderBand PageHeader;
        private DevExpress.XtraReports.UI.PageFooterBand PageFooter;
        private DevExpress.XtraReports.UI.DetailReportBand ITPDetail;
        private DevExpress.XtraReports.UI.TopMarginBand TopMargin;
        private DevExpress.XtraReports.UI.BottomMarginBand BottomMargin;
        private DevExpress.XtraReports.UI.XRPanel headPanel;
        private DevExpress.XtraReports.UI.XRLabel lbReportHeading;
        private DevExpress.XtraReports.UI.XRLabel lbProject;
        private DevExpress.XtraReports.UI.XRLabel lbRecordReference;
        private DevExpress.XtraReports.UI.XRPictureBox pbLogo;
        private DevExpress.XtraReports.UI.XRLabel lbFooterText;
        private DevExpress.XtraReports.UI.XRPageInfo xrPageInfo1;
        private DevExpress.XtraReports.UI.XRLabel lblFtrCenterText;
        private DevExpress.XtraReports.UI.DetailBand LotItpDetail_Detail;
        private DevExpress.XtraReports.UI.DetailReportBand ITPTest;
        private DevExpress.XtraReports.UI.ReportFooterBand ReportFooter;
        private DevExpress.XtraReports.UI.GroupHeaderBand GroupHeader1;
        private DevExpress.XtraReports.UI.GroupFooterBand pbGroupFooter;
        private DevExpress.XtraReports.UI.XRShape bxNCR;
        private DevExpress.XtraReports.UI.XRShape bxVerified;
        private DevExpress.XtraReports.UI.XRShape bxApproved;
        private DevExpress.XtraReports.UI.XRShape bxChecked;
        private DevExpress.XtraReports.UI.XRRichText xrrtDescription;
        private DevExpress.XtraReports.UI.XRLabel lbIndex;
        private DevExpress.XtraReports.UI.DetailBand ITPTest_Detail;
        private DevExpress.XtraReports.UI.XRLabel lbTest;
        private DevExpress.XtraReports.UI.XRLabel xrLabel1;
        private DevExpress.XtraReports.UI.XRRichText xrrtCompliance;
        private DevExpress.XtraReports.UI.XRLabel lblFreq;
        private DevExpress.DataAccess.ObjectBinding.ObjectDataSource objectDataSource1;
        private DevExpress.XtraReports.UI.SubBand sbFullHeader;
        private DevExpress.XtraReports.UI.SubBand sbShortHeader;
        private DevExpress.XtraReports.UI.XRPanel pnlHeader;
        private DevExpress.XtraReports.UI.XRLabel xrLabel6;
        private DevExpress.XtraReports.UI.XRLabel lblLot;
        private DevExpress.XtraReports.UI.XRLabel lblDateComp;
        private DevExpress.XtraReports.UI.XRLabel lblDateCompHeader;
        private DevExpress.XtraReports.UI.XRLabel lblDateOpenHeader;
        private DevExpress.XtraReports.UI.XRLabel lblDateOpen;
        private DevExpress.XtraReports.UI.XRLabel lblDateWorkStHeader;
        private DevExpress.XtraReports.UI.XRLabel lblDateWorkSt;
        private DevExpress.XtraReports.UI.XRLabel lbCheck;
        private DevExpress.XtraReports.UI.XRLabel lbVerify;
        private DevExpress.XtraReports.UI.XRLabel lbAppr;
        private DevExpress.XtraReports.UI.XRLabel lbNCR;
        private DevExpress.XtraReports.UI.SubBand sbQtyData;
        private DevExpress.XtraReports.UI.SubBand sbComment;
        private DevExpress.XtraReports.UI.SubBand sbShowSig;
        private DevExpress.XtraReports.UI.XRPanel pnlQty;
        private DevExpress.XtraReports.UI.XRPanel pnlComment;
        private DevExpress.XtraReports.UI.XRPanel pnlHeadings;
        private DevExpress.XtraReports.UI.XRPanel pnlRespOficer;
        private DevExpress.XtraReports.UI.XRPanel pnlVerAuth;
        private DevExpress.XtraReports.UI.XRLabel xrLabel8;
        private DevExpress.XtraReports.UI.XRLabel xrLabel9;
        private DevExpress.XtraReports.UI.XRLine xrLine6;
        private DevExpress.XtraReports.UI.XRLabel lbRespOffice;
        private DevExpress.XtraReports.UI.XRLine xrLine7;
        private DevExpress.XtraReports.UI.XRLine xrLine8;
        private DevExpress.XtraReports.UI.XRLabel xrLabel7;
        private DevExpress.XtraReports.UI.XRLine xrLine4;
        private DevExpress.XtraReports.UI.XRLabel xrLabel2;
        private DevExpress.XtraReports.UI.XRLine xrLine3;
        private DevExpress.XtraReports.UI.XRLine xrLine5;
        private DevExpress.XtraReports.UI.XRLabel xrLabel5;
        private DevExpress.XtraReports.UI.XRControlStyle Title;
        private DevExpress.XtraReports.UI.XRControlStyle FieldCaption;
        private DevExpress.XtraReports.UI.XRControlStyle PageInfo;
        private DevExpress.XtraReports.UI.XRControlStyle DataField;
    }
}
