//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cpReportDefinitions.TestReqRep {
    
    public partial class rptTR : rptTemplate
    {
        private void InitializeComponent() {
            DevExpress.XtraReports.ReportInitializer reportInitializer = new DevExpress.XtraReports.ReportInitializer(this, "cpReportDefinitions.TestReqRep.rptTR.repx");

            // Controls
            this.Detail = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("Detail");
            this.PageHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.PageHeaderBand>("PageHeader");
            this.PageFooter = reportInitializer.GetControl<DevExpress.XtraReports.UI.PageFooterBand>("PageFooter");
            this.DetailReport_Prop = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailReportBand>("DetailReport_Prop");
            this.DetailReport_TestList = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailReportBand>("DetailReport_TestList");
            this.DetailReport_TestGrouped = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailReportBand>("DetailReport_TestGrouped");
            this.TopMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.TopMarginBand>("TopMargin");
            this.BottomMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.BottomMarginBand>("BottomMargin");
            this.lbLocationMethod = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbLocationMethod");
            this.lbNotes = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbNotes");
            this.xrLabel21 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel21");
            this.lbTestReason = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbTestReason");
            this.xrLabel19 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel19");
            this.xrLabel20 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel20");
            this.xrLabel17 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel17");
            this.XrLabel23 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("XrLabel23");
            this.XrLabel18 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("XrLabel18");
            this.XrLabel16 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("XrLabel16");
            this.XrLabel7 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("XrLabel7");
            this.XrLabel6 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("XrLabel6");
            this.XrLabel5 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("XrLabel5");
            this.XrLabel4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("XrLabel4");
            this.XrLabel2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("XrLabel2");
            this.XrLabel1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("XrLabel1");
            this.XrLabel9 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("XrLabel9");
            this.XrLabel11 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("XrLabel11");
            this.XrLabel8 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("XrLabel8");
            this.XrLabel12 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("XrLabel12");
            this.XrLabel13 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("XrLabel13");
            this.XrLabel10 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("XrLabel10");
            this.XrLabel14 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("XrLabel14");
            this.XrLabel3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("XrLabel3");
            this.XrLabel15 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("XrLabel15");
            this.XrLabel31 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("XrLabel31");
            this.XrLabel32 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("XrLabel32");
            this.XrLabel35 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("XrLabel35");
            this.XrLabel36 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("XrLabel36");
            this.headPanel = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPanel>("headPanel");
            this.lbReportHeading = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbReportHeading");
            this.lbProject = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbProject");
            this.lbRecordReference = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbRecordReference");
            this.pbLogo = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPictureBox>("pbLogo");
            this.lbFooterText = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbFooterText");
            this.xrPageInfo1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPageInfo>("xrPageInfo1");
            this.Detail_Prop = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("Detail_Prop");
            this.ReportHeader_Prop = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportHeaderBand>("ReportHeader_Prop");
            this.xrLabel22 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel22");
            this.xrLabel24 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel24");
            this.xrLabel37 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel37");
            this.Detail_TestList = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("Detail_TestList");
            this.ReportHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportHeaderBand>("ReportHeader");
            this.xrPanel2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPanel>("xrPanel2");
            this.xrLabel34 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel34");
            this.xrLabel38 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel38");
            this.xrLabel39 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel39");
            this.xrLabel40 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel40");
            this.xrLabel41 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel41");
            this.xrLabel33 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel33");
            this.sbCompliance = reportInitializer.GetControl<DevExpress.XtraReports.UI.SubBand>("sbCompliance");
            this.xrPanel5 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPanel>("xrPanel5");
            this.xrCompliance = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrCompliance");
            this.xrLabel42 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel42");
            this.xrPanel1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPanel>("xrPanel1");
            this.lbhLot = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbhLot");
            this.xrLabel26 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel26");
            this.xrLabel27 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel27");
            this.xrLabel28 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel28");
            this.xrLabel29 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel29");
            this.xrLabel30 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel30");
            this.Detail_TestGrouped = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("Detail_TestGrouped");
            this.ReportHeader_TestGrouped = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportHeaderBand>("ReportHeader_TestGrouped");
            this.xrPanel4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPanel>("xrPanel4");
            this.lbTestMeth = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbTestMeth");
            this.lbScheduleItem = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbScheduleItem");
            this.lbNoTests = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbNoTests");
            this.sbComplianceGrouped = reportInitializer.GetControl<DevExpress.XtraReports.UI.SubBand>("sbComplianceGrouped");
            this.panel1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPanel>("panel1");
            this.xrComplianceGrouped = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrComplianceGrouped");
            this.label1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label1");
            this.xrPanel3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPanel>("xrPanel3");
            this.lbhDescription = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbhDescription");
            this.xrLabel25 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel25");
            this.lbhRPF = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbhRPF");
            this.DetailReport_customreg = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailReportBand>("DetailReport_customreg");
            this.Detail1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("Detail1");
            this.ReportHeader1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportHeaderBand>("ReportHeader1");
            this.label3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label3");
            this.label4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label4");
            this.label5 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label5");

            // Data Sources
            this.objectDataSource1 = reportInitializer.GetDataSource<DevExpress.DataAccess.ObjectBinding.ObjectDataSource>("objectDataSource1");
            this.objectDataSource1.DataSource = typeof(cpModel.Dtos.Report.TestRequestReportDto);

            // Styles
            this.Title = reportInitializer.GetStyle("Title");
            this.FieldCaption = reportInitializer.GetStyle("FieldCaption");
            this.PageInfo = reportInitializer.GetStyle("PageInfo");
            this.DataField = reportInitializer.GetStyle("DataField");
        }
        private DevExpress.XtraReports.UI.DetailBand Detail;
        private DevExpress.XtraReports.UI.PageHeaderBand PageHeader;
        private DevExpress.XtraReports.UI.PageFooterBand PageFooter;
        private DevExpress.XtraReports.UI.DetailReportBand DetailReport_Prop;
        private DevExpress.XtraReports.UI.DetailReportBand DetailReport_TestList;
        private DevExpress.XtraReports.UI.DetailReportBand DetailReport_TestGrouped;
        private DevExpress.XtraReports.UI.TopMarginBand TopMargin;
        private DevExpress.XtraReports.UI.BottomMarginBand BottomMargin;
        private DevExpress.XtraReports.UI.XRLabel lbLocationMethod;
        private DevExpress.XtraReports.UI.XRLabel lbNotes;
        private DevExpress.XtraReports.UI.XRLabel xrLabel21;
        private DevExpress.XtraReports.UI.XRLabel lbTestReason;
        private DevExpress.XtraReports.UI.XRLabel xrLabel19;
        private DevExpress.XtraReports.UI.XRLabel xrLabel20;
        private DevExpress.XtraReports.UI.XRLabel xrLabel17;
        private DevExpress.XtraReports.UI.XRLabel XrLabel23;
        private DevExpress.XtraReports.UI.XRLabel XrLabel18;
        private DevExpress.XtraReports.UI.XRLabel XrLabel16;
        private DevExpress.XtraReports.UI.XRLabel XrLabel7;
        private DevExpress.XtraReports.UI.XRLabel XrLabel6;
        private DevExpress.XtraReports.UI.XRLabel XrLabel5;
        private DevExpress.XtraReports.UI.XRLabel XrLabel4;
        private DevExpress.XtraReports.UI.XRLabel XrLabel2;
        private DevExpress.XtraReports.UI.XRLabel XrLabel1;
        private DevExpress.XtraReports.UI.XRLabel XrLabel9;
        private DevExpress.XtraReports.UI.XRLabel XrLabel11;
        private DevExpress.XtraReports.UI.XRLabel XrLabel8;
        private DevExpress.XtraReports.UI.XRLabel XrLabel12;
        private DevExpress.XtraReports.UI.XRLabel XrLabel13;
        private DevExpress.XtraReports.UI.XRLabel XrLabel10;
        private DevExpress.XtraReports.UI.XRLabel XrLabel14;
        private DevExpress.XtraReports.UI.XRLabel XrLabel3;
        private DevExpress.XtraReports.UI.XRLabel XrLabel15;
        private DevExpress.XtraReports.UI.XRLabel XrLabel31;
        private DevExpress.XtraReports.UI.XRLabel XrLabel32;
        private DevExpress.XtraReports.UI.XRLabel XrLabel35;
        private DevExpress.XtraReports.UI.XRLabel XrLabel36;
        private DevExpress.XtraReports.UI.XRPanel headPanel;
        private DevExpress.XtraReports.UI.XRLabel lbReportHeading;
        private DevExpress.XtraReports.UI.XRLabel lbProject;
        private DevExpress.XtraReports.UI.XRLabel lbRecordReference;
        private DevExpress.XtraReports.UI.XRPictureBox pbLogo;
        private DevExpress.XtraReports.UI.XRLabel lbFooterText;
        private DevExpress.XtraReports.UI.XRPageInfo xrPageInfo1;
        private DevExpress.XtraReports.UI.DetailBand Detail_Prop;
        private DevExpress.XtraReports.UI.ReportHeaderBand ReportHeader_Prop;
        private DevExpress.XtraReports.UI.XRLabel xrLabel22;
        private DevExpress.XtraReports.UI.XRLabel xrLabel24;
        private DevExpress.XtraReports.UI.XRLabel xrLabel37;
        private DevExpress.XtraReports.UI.DetailBand Detail_TestList;
        private DevExpress.XtraReports.UI.ReportHeaderBand ReportHeader;
        private DevExpress.XtraReports.UI.XRPanel xrPanel2;
        private DevExpress.XtraReports.UI.XRLabel xrLabel34;
        private DevExpress.XtraReports.UI.XRLabel xrLabel38;
        private DevExpress.XtraReports.UI.XRLabel xrLabel39;
        private DevExpress.XtraReports.UI.XRLabel xrLabel40;
        private DevExpress.XtraReports.UI.XRLabel xrLabel41;
        private DevExpress.XtraReports.UI.XRLabel xrLabel33;
        private DevExpress.XtraReports.UI.SubBand sbCompliance;
        private DevExpress.XtraReports.UI.XRPanel xrPanel5;
        private DevExpress.XtraReports.UI.XRRichText xrCompliance;
        private DevExpress.XtraReports.UI.XRLabel xrLabel42;
        private DevExpress.XtraReports.UI.XRPanel xrPanel1;
        private DevExpress.XtraReports.UI.XRLabel lbhLot;
        private DevExpress.XtraReports.UI.XRLabel xrLabel26;
        private DevExpress.XtraReports.UI.XRLabel xrLabel27;
        private DevExpress.XtraReports.UI.XRLabel xrLabel28;
        private DevExpress.XtraReports.UI.XRLabel xrLabel29;
        private DevExpress.XtraReports.UI.XRLabel xrLabel30;
        private DevExpress.XtraReports.UI.DetailBand Detail_TestGrouped;
        private DevExpress.XtraReports.UI.ReportHeaderBand ReportHeader_TestGrouped;
        private DevExpress.XtraReports.UI.XRPanel xrPanel4;
        private DevExpress.XtraReports.UI.XRLabel lbTestMeth;
        private DevExpress.XtraReports.UI.XRLabel lbScheduleItem;
        private DevExpress.XtraReports.UI.XRLabel lbNoTests;
        private DevExpress.XtraReports.UI.SubBand sbComplianceGrouped;
        private DevExpress.XtraReports.UI.XRPanel panel1;
        private DevExpress.XtraReports.UI.XRRichText xrComplianceGrouped;
        private DevExpress.XtraReports.UI.XRLabel label1;
        private DevExpress.XtraReports.UI.XRPanel xrPanel3;
        private DevExpress.XtraReports.UI.XRLabel lbhDescription;
        private DevExpress.XtraReports.UI.XRLabel xrLabel25;
        private DevExpress.XtraReports.UI.XRLabel lbhRPF;
        private DevExpress.XtraReports.UI.XRControlStyle Title;
        private DevExpress.XtraReports.UI.XRControlStyle FieldCaption;
        private DevExpress.XtraReports.UI.XRControlStyle PageInfo;
        private DevExpress.XtraReports.UI.XRControlStyle DataField;
        private DevExpress.DataAccess.ObjectBinding.ObjectDataSource objectDataSource1;
        private DevExpress.XtraReports.UI.DetailReportBand DetailReport_customreg;
        private DevExpress.XtraReports.UI.DetailBand Detail1;
        private DevExpress.XtraReports.UI.ReportHeaderBand ReportHeader1;
        private DevExpress.XtraReports.UI.XRLabel label3;
        private DevExpress.XtraReports.UI.XRLabel label4;
        private DevExpress.XtraReports.UI.XRLabel label5;
    }
}
