using System;
using System.Linq;

namespace cpModel.Enums
{
    public enum PermissionDomainEnum
    {
        Dashboard = 1,
        Notification = 2,
        Lot = 5,
        Ncr = 10,
        Test = 15,
        Checklist = 20,
        Approval = 25,
        Quantity = 30,
        Itp = 35,
        Photo = 40,
        Filestore = 45,
        Email = 50,
        Contact = 55,
        Unit = 60,
        Tag = 65,
        Atp = 70,
        Survey = 80,
        PunchList = 90,
        Variation = 100,
        Progress_Claim = 105,
        Document = 200,
        Contract_Notice = 205,
        Site_Diary = 300,
        Instruction = 305,
        Incident = 310,
        Risk = 315,
        Daycost = 400,
        Invoice = 405,
        Purchase_Order = 410,
        Receipt = 415,
        Forecast = 420,
        Work_Type = 500,
        Area_Code = 505,
        Control_Line = 510,
        Test_Method = 515,
        Test_Property = 520,
        LotMap_Definition = 530,
        Schedule_Item = 600,
        Supplier_link = 605,
        Resource = 610,
        Cost_code = 615,
        Custom_Register = 620,
        Custom_Reports = 630,
        Project_administration = 700,
        Notification_Template = 800,
        Contract_Notice_Template = 805,
        Workflow = 810,
        Master_Supplier = 905,
        Subcontractor_Management = 910,
        Group = 920,
        CrossProject_administration = 950,
        Conform_Lot = 1000,
        Guarantee_Lot = 1010,
        Publish_Ncr = 1020,
        Publish_Approval = 1025,
        Itp_Approve_Internal = 1050,
        Checklist_Check = 1100,
        Checklist_Verify = 1105,
        Checklist_Approve_Internal = 1110,
        Approval_Collaborate_HPWP = 1115,
        Approval_Collaborate_NCR = 1200,
        Approval_Collaborate_Independent = 1250,
        Approval_View_Private = 1260,
        Cross_Project_Finance = 1400,
        Cross_Project_HSEQ = 1405,
        Test_Request_Collaborate = 1500,
        Survey_Collaborate = 1550,
        Contract_Notice_Collaborate = 1600,
        Limit_Ncr_View_To_Published = 1700,
        Limit_TestReq_View_To_Completed = 1710,
        Subcontractor = 2000,
        GeneralAccess = 100000,
        Administration = 200000,
        //The Subscription_administration is never actually granted. It is a place holder for form permissions such that
        //the test for the permission is whether the user is a subscription admin as assigned in the switch on the user table.
        //e.g. User.IsSubscriberAdmin
        Subscription_administration = 400000
    }
}
